name: project-euler-haskell
version: 0.1.0.0
github: "lccro/project-euler-haskell"
license: BSD3
author: "Cyber"
maintainer: "lccro@msn.com"
copyright: "Copyleft 2020"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/lccro/project-euler-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - primes
  - text
  - hspec
  - time
  - split
  - containers

library:
  source-dirs: src

executables:
  project-euler-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - project-euler-haskell

tests:
  project-euler-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - project-euler-haskell
